name:                a3
version:             0.1.0.0
github:              "paulsattlegger/ps23"
license:             Apache-2.0

dependencies:
- base >= 4.7 && < 5
- brick
- microlens-platform
- megaparsec
- text
- vty

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  a3-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - a3
    when:        
    - condition: false        
      other-modules: Paths_a3

tests:
  a3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - a3
